### ISSUE TITLE
Beküldhető filetípusok

### ISSUE THREAD

**Issue by tothj74** [nav-gov-hu/M2M#47]
Üdv
A dokumentációban nem találtam erre vonatkozóan korlátozást, de mindenképp szeretném tisztázni a kérdést: a beküldött file imp formátumú is lehet?

**Comment by TamasPill** [comment]
Nem, csak a tiszta xml formátumot lehet beküldeni.
Ez ÁNYK-ban az Adatok/XML állomány mentése funkció.

**Comment by tothj74** [comment]
Köszönöm a gyors választ.
